#!/usr/bin/env bash
# Configures localhost and facebook.com IP resolution

cp /etc/hosts /tmp/hosts.new

sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /tmp/hosts.new

if grep -q "facebook.com" /tmp/hosts.new; then
    sed -i 's/^.*facebook\.com$/8.8.8.8 facebook.com/' /tmp/hosts.new
else
    echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
fi

cp /tmp/hosts.new /etc/hosts
